// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9DFglqp1fLaP3TA9885yGZ5szwlrgmxI',
    appId: '1:106135886192:web:2a2287b100fef5e6a917b5',
    messagingSenderId: '106135886192',
    projectId: 'pmetal-643d7',
    authDomain: 'pmetal-643d7.firebaseapp.com',
    storageBucket: 'pmetal-643d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpP2zx7rkebYOgB0rAXCY53XWZ_ZOl368',
    appId: '1:106135886192:android:4c3e18f73fc73eb3a917b5',
    messagingSenderId: '106135886192',
    projectId: 'pmetal-643d7',
    storageBucket: 'pmetal-643d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPvHs-Dk873kJQHhYLtJIMIjYE0T1gS8',
    appId: '1:106135886192:ios:ffd82770899ae26da917b5',
    messagingSenderId: '106135886192',
    projectId: 'pmetal-643d7',
    storageBucket: 'pmetal-643d7.appspot.com',
    iosBundleId: 'com.example.pmprod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnPvHs-Dk873kJQHhYLtJIMIjYE0T1gS8',
    appId: '1:106135886192:ios:c02ab9cd669bfa86a917b5',
    messagingSenderId: '106135886192',
    projectId: 'pmetal-643d7',
    storageBucket: 'pmetal-643d7.appspot.com',
    iosBundleId: 'com.example.pmprod.RunnerTests',
  );
}
